.TH sleepmemtester "8" "July 2021" "sleepmemtester 4" "Maintenance Commands"
.SH NAME
sleepmemtester \- Simple memory test to find system hardware/firmware issue on sleep/resume memory initialization.
.SH SYNOPSIS
.B sleepmemtester
[\f -p PHYSADDR\fR [\f -d DEVICE\fR]]
<\fIMEMORY\fR>
[\fIITERATIONS\fR]
.SH DESCRIPTION
.\" Add any additional description here
.PP
sleepmemtester is an effective memory tester for system sleep/resume memory
test. The purpose for develop sleepmemtester is there are too many memory
issues after system retore from sleep state. Especially in system board
bring up/firmware development phase. Sometimes system run into error state
but we don't know the root cause. sleepmemtester can help to verify if
system memory changed after resume. sleepmemtester will also display the
physical address of the corrupted memory, which is very helpful on hardware
and firmware debug.
sleepmemtester is developed based on memtester. Some key function such as
mlock is using the memtester code. And main function changed since sleepmemtester
has the differenet purpose with memtester.
.PP
.SH OPTIONS
.TP
\f -p PHYSADDR\fR
tells sleepmemtester to test a specific region of memory starting at physical
address PHYSADDR (given in hex), by mmap(2)ing a device specified by the
-d option (below, or /dev/mem by default).  This is mostly of use to hardware
developers, for testing memory-mapped I/O devices and similar.
Note that the memory region will be overwritten during testing, so it is not
safe to specify memory which is allocated for the system or for other
applications; doing so will cause them to crash.  If you absolutely must test
a particular region of actual physical memory, arrange to have that memory
allocated by your test software, and hold it in this allocated state, then
run sleepmemtester on it with this option.
-m option (default mem). This is used for sleep type select. Currently only
Suspend to ram (S3) and Hibernate (S4) are supported.
-s option (default 40). This is used for sleep timer setting. System will
automaticlly wake after sleeptimer timeout.
-t option (default 30). This is used for wakeup timer setting. System will
automaticlly sleep after wake timer timeout.
-v option (default 0xFFFFFFFFFFFFFFFF). This is used for special test value
setting. Sometimes memory data changed from 1->0 sometimes 0->1, choose it
based on your verification.
.TP
\fIMEMORY\fR
the amount of memory to allocate and test, in megabytes by default.  You can
include a suffix of B, K, M, or G to indicate bytes, kilobytes, megabytes, or
gigabytes respectively.
.TP
\fIITERATIONS\fR
(optional) number of loops to iterate through.  Default is infinite.
.SH NOTE
.PP
sleepmemtester must be run with root privileges to mlock(3) its pages.  Testing
memory without locking the pages in place is mostly pointless and slow.
.SH EXIT CODE
.PP
sleepmemtester's exit code is 0 when everything works properly.  Otherwise,
it is the logical OR of the following values:
.TP
\f0x01
error allocating or locking memory, or invocation error
.TP
\f0x02
error during stuck address test
.TP
\f0x04
error during one of the other tests
.SH AUTHOR
Written by Jonathan Wang.
.SH "REPORTING BUGS"
Report bugs to <juquanff@gmail.com>.
.PP
.SH COPYRIGHT
Copyright \(co 2021 Jonathan Wang
.br
This is free software; see the file COPYING for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
